Algoritmo "calcular area do triangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : esse programa calcula a aréa de um triangulo
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
base: inteiro
altura: inteiro
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai calcular a areá de um triangulo")
escreval
escreva("digite qual é a base do triangulo:")
leia(base)
escreva("digite a altura agora:")
leia(altura)
area<- base*altura/2
escreva("o resultado da aréa do triangulo é :",area)


Fimalgoritmo