Algoritmo "Atividade 33"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis

   num1,num2:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("digite um valor: ")
   leia(num1)
   escreva("digite outro número :")
   leia(num2)
   se num1>num2 entao
      escreval(" O primeiro valor é o maior")
   senao
      se num2>num1 entao
         escreval("o segundo número é o maior")

      senao
         escreval("os números são iguais")

      fimse
   fimse



Fimalgoritmo