Algoritmo "Atividade 27positivo,negativo ou zero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 22/03/2025

Var
   // Seção de Declarações das variáveis
   valor1:real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("digite um valor :")
   leia(valor1)
   se valor1< -0 entao
      escreval("esse valor é negativo")
   senao
      se valor1=0 entao
         escreval("esse valor é zero")

      senao
         escreval("esse valor é positivo")

      fimse
   fimse

Fimalgoritmo