Algoritmo "Atividade 10, Acertar senha"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2025
Var
   // Seção de Declarações das variáveis
   correta,senha:caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   correta<- "Guxtatec"


   escreval("digite sua senha de acesso")
   leia(senha)
   enquanto senha <> correta faca
      escreval("senha Errada digite novamente :")
      leia(senha)


   fimenquanto
   
   escreval("acesso permitido")


Fimalgoritmo