Algoritmo "Atividade ¨do whats 09 fatorial  "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2025
Var
   // Seção de Declarações das variáveis
   numero  :inteiro
   fatorial:inteiro






Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   fatorial<- 1
   escreval("Digite um número:")
   leia(numero)
   enquanto numero >= 1 faca
      fatorial<- fatorial*numero
      numero<- numero-1
      fimenquanto
      escrevaL("O fatorial do número é " ,numero," é ",fatorial)


Fimalgoritmo