Algoritmo "até 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2025
Var
// Seção de Declarações das variáveis 
numero:inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("números até o 10")
numero<- 1
enquanto numero <=10 faca
escreva(numero)
numero<-numero +1
fimenquanto



Fimalgoritmo