Algoritmo "calcular area do Hexagono"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : esse programa calcula a aréa de um Hexagono
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
lado: inteiro
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai calcular a areá de um Hexagono")
escreval

escreva("digite qual é lado do Hexagono:")
leia(lado)


area<- 3*lado^2*raizq(3)/2
escreva("o resultado da aréa do Hexagono é :",area:0:2,"cm")


Fimalgoritmo