Algoritmo "calcular area do quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : esse programa calcula a aréa de um quadrado
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
lado: inteiro

area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai calcular a areá de um quadrado")
escreval
escreva("Qual o valor do de um lado do quadrado:")
leia(lado)
escreval
area<- lado*lado
escreva("o resultado da aréa do quadrado é :",area)


Fimalgoritmo
