Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : calcular a aréa do circulo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
raio:real
area:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Esse programa vai calcular a aréa do circulo")
escreval  ("")
escreva ("digite o raio  do circulo :")
leia (raio)

area <- raio*valor*pi
escreva("o resultado da aréa do circulo", areav"cm")





Fimalgoritmo