Algoritmo "contagem regressiva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de Souza Santos
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis

   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("contagem regressiva")
   escreval
   escreva("digite um número")
   leia(numero)
   enquanto numero > 0 faça
      numero<- numero- 1
      escreval(numero)
   fimenquanto




Fimalgoritmo