Algoritmo "Contador de 1 a 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
      contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("contador de 1 a 10")
   escreval("")
   contador<- 1
   enquanto (contador <=10) faca
      escreval(contador)
      contador<- contador + 1
   fimenquanto




Fimalgoritmo