Algoritmo "Contador de pares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Contador de pares")
   escreval
   numero<- 2
   enquanto numero<=20 faca
      se numero mod 2=0 entao
         escreval(numero)
      fimse
      numero<- numero+2
      fimenquanto





Fimalgoritmo