Algoritmo "DesvioscompacionarSimples"
// Disciplina   : [Linguagem e Lógica de Programação com visualg]
// Professor   : Jaja
// Descrição   : Solicitar um valor e se for menor que 10, exibir uma mensagem
// Autor(a)    : Gustavo Henrique
// Data atual  : 17/03/2025
Var
   // Seção de Declarações das variáveis
   valor: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" digite um número")
   leia(valor)
   se valor<10 então
   escreval(" esse número é menor que 10 :")
   fimse



Fimalgoritmo