Algoritmo "Desviocondicionarcomposto"
// Disciplina   : [Linguagem e Lógica de Programação com visualG]
// Professor   : Jaja
// Descrição   : Solicite um número e verifique se é maior ou menor 10
// Autor(a)    : Gustavo Henrique
// Data atual  : 17/03/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("digite um número")
   leia(numero)
   se numero< 10 entao
   escreval("número digitado é menor que 10")
   senao numero> 10 entao
   escreval ("esse número é  que 10 ")
   fimse
Fimalgoritmo
