Algoritmo "Dividir"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! ()
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
num01: inteiro
num02: inteiro
dividir:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai realizar a divisão de dois número")
escreval
escreva("Digite um número : ")
leia (num01)
escreva("escreva outro número :")
leia(num02)
dividir <- num01 / num02
escreva("o resultado da divisão é ", dividir)



Fimalgoritmo