Algoritmo "Estrutura de repetição "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis
x:inteiro
r:inteiro
cont:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 1
enquanto (cont <=5) faca
escreva("digite um número :")
leia(x)
r <- x*3
escreval("o resultado é",r)

cont<- cont +1
fimenquanto



Fimalgoritmo