Algoritmo "Exemplodeescolhaacaso"
// Disciplina    [Linguagem e Lógica de Programação]
// Professor    Antonio Carlos Nicolodi
// Descrição    Testedo Desvio condicionar ecadeado
// Autor(a)     Nome do(a) aluno(a)
// Data atual   21/03/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("")
   escreval("digite um número de 1 a 7")
   escreval("")
   leia(numero)

   escolha numero
   caso 1
      escreval("hoje é domingo")
      
   caso 2
      escreval("hoje é segunda")
      
   caso 3
      escreval("hoje é terça")
      
   caso 4
      escreval("hoje é quarta")
      
   caso 5
      escreval("hoje é quinta")
      
   caso 6
      escreval("hoje é sexta")
      
   caso 7
      escreval("hoje é sabado ")
      
   outrocaso
      escreval("não foi um valor de 1 a 7")
      fimescolha








Fimalgoritmo