Algoritmo "Exercicio 16faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo
// Data atual  : 19/03/2025
Var
   // Seção de Declarações das variáveis
   valor:real
   soma:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("quantas maças voçê comprou?: ")
   leia(valor)

   se valor >11 entao
      escreval (" o valor total deu:",valor,"R$")
   senao
      soma<- valor*1.30
      escreval("você não teve desconto o valor foi",soma,"R$")
   fimse


Fimalgoritmo
