Algoritmo "Exercicio 15faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo
// Data atual  : 19/03/2025
Var
// Seção de Declarações das variáveis 
numero:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um número para analisamos se é positivo ou negativo :")
leia(numero)
se  numero>-1  então
escreval(" esse número é positivo")
senao
escreval("esse número é negativo")

fimse


Fimalgoritmo