Algoritmo "impares e pares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2025
Var
// Seção de Declarações das variáveis 
contador:inteiro
pares:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("contador até o de impares até 20")
contador<- 1

enquanto contador <= 20 faca

escreva(contador)
contador<- contador+2

fimenquanto
escreval("")

escreval("contador de números pares até 20 ")
pares<- 2
enquanto pares<= 20 faca
escreval(pares)
pares<- pares+2
fimenquanto


Fimalgoritmo