Algoritmo "losango"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : esse programa calcula a aréa de um rosango
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
mm: inteiro
mn: inteiro
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai calcular a areá de um rosango")
escreval
escreva("digite a maior medida do lorango:")
leia(mm)
escreva("digite a menor medida do lorango:")
leia(mn)
area<- mm*mn/2
escreva("o resultado da aréa do lorango é :",area)


Fimalgoritmo