Algoritmo "SOMA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (Soma de dois números)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
num01: inteiro
num02: inteiro
multi:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("  esse programa vai fazer a multiplicação de dois números")
escreval
escreva("digite um número: ")
leia(num01)
escreva("digite outro número :")
leia(num02)
multi<- num01 * num02
escreva("o resultado da multiplicacação é ", multi  )


Fimalgoritmo