Algoritmo "numeros pares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
   numero:inteiro



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("contador de pares")
   escreval("")
   numero<- 2
   enquanto numero <= 20 faça
      se numero mod 2=0 entao
         escreval(numero)
         fimse
         numero<- numero + 2
         fimenquanto


Fimalgoritmo