Algoritmo "SOMA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jainsol
// Descrição   : Aqui você descreve o que o programa faz! (Soma de dois números)
// Autor(a)    : Gustavo Henrique de souza santos
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis
num01: inteiro
num02: inteiro
soma:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" esse programa vai fazer a soma de dois número")
escreval
escreva("digite um número :")
leia(num01)
escreva("digite outro número :")
leia(num02)
soma<- num01 + num02
escreva("o valor da soma é ",soma)


Fimalgoritmo