Algoritmo "Somando com o repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis
num,total:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("vamos jogar um jogo")
total<- 0
repita

escreva("digite um número:")
leia(num)
total<- total+num


ate num<=0

escreval(" o valor total de todos os números é :",total)


Fimalgoritmo