Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis
numero:inteiro
multi:inteiro
contador: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("TABUADA")
escreval("")
escreva("digite um número :")
contador<- 1
leia(numero)
enquanto contador <= 10 faça
multi<- contador* numero
escreva(multi)
contador<- contador + 1
fimenquanto




Fimalgoritmo