Algoritmo "time"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2025
Var
   // Seção de Declarações das variáveis
   contador1,contador2,contador3,time:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contador3 de 0 ate 23 passo 1 faca
      para contador1 de 0 ate 59 passo 1 faca
         para contador2 de 0 ate 59 passo 1 faca
            escreval(contador3," Hora "," Min ",contador1, ":","Segundos",contador2)

         fimpara
      fimpara

   fimpara



Fimalgoritmo