Algoritmo "trapezio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jaja
// Descrição   : calcular a aréa do trapezio
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis 
base01:inteiro
base02:inteiro
altura:inteiro
area:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Esse programa vai calcular a aréa do trapézio")
escreval  ("")
escreva ("digite a base maior do trapézio :")
leia (base01)

escreva(" digite a base menor agora : ")
leia(base02)

escreva("digite a altura do trapézio :")
leia(altura)
area <- (base01+base02)*altura/2
escreva("o resultado da aréa do trapézio", area)





Fimalgoritmo